// Generated by gencpp from file dobot/GetHHTTrigMode.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_GETHHTTRIGMODE_H
#define DOBOT_MESSAGE_GETHHTTRIGMODE_H

#include <ros/service_traits.h>


#include <dobot/GetHHTTrigModeRequest.h>
#include <dobot/GetHHTTrigModeResponse.h>


namespace dobot
{

struct GetHHTTrigMode
{

typedef GetHHTTrigModeRequest Request;
typedef GetHHTTrigModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetHHTTrigMode
} // namespace dobot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot::GetHHTTrigMode > {
  static const char* value()
  {
    return "1abcbcf9addf5b1ea080766e6d75545f";
  }

  static const char* value(const ::dobot::GetHHTTrigMode&) { return value(); }
};

template<>
struct DataType< ::dobot::GetHHTTrigMode > {
  static const char* value()
  {
    return "dobot/GetHHTTrigMode";
  }

  static const char* value(const ::dobot::GetHHTTrigMode&) { return value(); }
};


// service_traits::MD5Sum< ::dobot::GetHHTTrigModeRequest> should match 
// service_traits::MD5Sum< ::dobot::GetHHTTrigMode > 
template<>
struct MD5Sum< ::dobot::GetHHTTrigModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::GetHHTTrigMode >::value();
  }
  static const char* value(const ::dobot::GetHHTTrigModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::GetHHTTrigModeRequest> should match 
// service_traits::DataType< ::dobot::GetHHTTrigMode > 
template<>
struct DataType< ::dobot::GetHHTTrigModeRequest>
{
  static const char* value()
  {
    return DataType< ::dobot::GetHHTTrigMode >::value();
  }
  static const char* value(const ::dobot::GetHHTTrigModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot::GetHHTTrigModeResponse> should match 
// service_traits::MD5Sum< ::dobot::GetHHTTrigMode > 
template<>
struct MD5Sum< ::dobot::GetHHTTrigModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::GetHHTTrigMode >::value();
  }
  static const char* value(const ::dobot::GetHHTTrigModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::GetHHTTrigModeResponse> should match 
// service_traits::DataType< ::dobot::GetHHTTrigMode > 
template<>
struct DataType< ::dobot::GetHHTTrigModeResponse>
{
  static const char* value()
  {
    return DataType< ::dobot::GetHHTTrigMode >::value();
  }
  static const char* value(const ::dobot::GetHHTTrigModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_MESSAGE_GETHHTTRIGMODE_H
