// Generated by gencpp from file dobot/GetInfraredSensorResponse.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_GETINFRAREDSENSORRESPONSE_H
#define DOBOT_MESSAGE_GETINFRAREDSENSORRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dobot
{
template <class ContainerAllocator>
struct GetInfraredSensorResponse_
{
  typedef GetInfraredSensorResponse_<ContainerAllocator> Type;

  GetInfraredSensorResponse_()
    : result(0)
    , value(0)  {
    }
  GetInfraredSensorResponse_(const ContainerAllocator& _alloc)
    : result(0)
    , value(0)  {
  (void)_alloc;
    }



   typedef int32_t _result_type;
  _result_type result;

   typedef uint8_t _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::dobot::GetInfraredSensorResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dobot::GetInfraredSensorResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetInfraredSensorResponse_

typedef ::dobot::GetInfraredSensorResponse_<std::allocator<void> > GetInfraredSensorResponse;

typedef boost::shared_ptr< ::dobot::GetInfraredSensorResponse > GetInfraredSensorResponsePtr;
typedef boost::shared_ptr< ::dobot::GetInfraredSensorResponse const> GetInfraredSensorResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dobot::GetInfraredSensorResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dobot::GetInfraredSensorResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dobot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'dobot': ['/home/kermit/dobot_ws/src/dobot/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dobot::GetInfraredSensorResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot::GetInfraredSensorResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot::GetInfraredSensorResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot::GetInfraredSensorResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot::GetInfraredSensorResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot::GetInfraredSensorResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dobot::GetInfraredSensorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "73a59c0cb161215c2b7c0a18034c4f90";
  }

  static const char* value(const ::dobot::GetInfraredSensorResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x73a59c0cb161215cULL;
  static const uint64_t static_value2 = 0x2b7c0a18034c4f90ULL;
};

template<class ContainerAllocator>
struct DataType< ::dobot::GetInfraredSensorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dobot/GetInfraredSensorResponse";
  }

  static const char* value(const ::dobot::GetInfraredSensorResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dobot::GetInfraredSensorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 result\n"
"uint8 value\n"
"\n"
"\n"
;
  }

  static const char* value(const ::dobot::GetInfraredSensorResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dobot::GetInfraredSensorResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetInfraredSensorResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dobot::GetInfraredSensorResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dobot::GetInfraredSensorResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<int32_t>::stream(s, indent + "  ", v.result);
    s << indent << "value: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOBOT_MESSAGE_GETINFRAREDSENSORRESPONSE_H
