// Generated by gencpp from file dobot/GetInfraredSensor.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_GETINFRAREDSENSOR_H
#define DOBOT_MESSAGE_GETINFRAREDSENSOR_H

#include <ros/service_traits.h>


#include <dobot/GetInfraredSensorRequest.h>
#include <dobot/GetInfraredSensorResponse.h>


namespace dobot
{

struct GetInfraredSensor
{

typedef GetInfraredSensorRequest Request;
typedef GetInfraredSensorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetInfraredSensor
} // namespace dobot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot::GetInfraredSensor > {
  static const char* value()
  {
    return "ae37af035c9c90c336594d3bdcbccceb";
  }

  static const char* value(const ::dobot::GetInfraredSensor&) { return value(); }
};

template<>
struct DataType< ::dobot::GetInfraredSensor > {
  static const char* value()
  {
    return "dobot/GetInfraredSensor";
  }

  static const char* value(const ::dobot::GetInfraredSensor&) { return value(); }
};


// service_traits::MD5Sum< ::dobot::GetInfraredSensorRequest> should match 
// service_traits::MD5Sum< ::dobot::GetInfraredSensor > 
template<>
struct MD5Sum< ::dobot::GetInfraredSensorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::GetInfraredSensor >::value();
  }
  static const char* value(const ::dobot::GetInfraredSensorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::GetInfraredSensorRequest> should match 
// service_traits::DataType< ::dobot::GetInfraredSensor > 
template<>
struct DataType< ::dobot::GetInfraredSensorRequest>
{
  static const char* value()
  {
    return DataType< ::dobot::GetInfraredSensor >::value();
  }
  static const char* value(const ::dobot::GetInfraredSensorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot::GetInfraredSensorResponse> should match 
// service_traits::MD5Sum< ::dobot::GetInfraredSensor > 
template<>
struct MD5Sum< ::dobot::GetInfraredSensorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::GetInfraredSensor >::value();
  }
  static const char* value(const ::dobot::GetInfraredSensorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::GetInfraredSensorResponse> should match 
// service_traits::DataType< ::dobot::GetInfraredSensor > 
template<>
struct DataType< ::dobot::GetInfraredSensorResponse>
{
  static const char* value()
  {
    return DataType< ::dobot::GetInfraredSensor >::value();
  }
  static const char* value(const ::dobot::GetInfraredSensorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_MESSAGE_GETINFRAREDSENSOR_H
