// Generated by gencpp from file dobot/SetHHTTrigOutputEnabledRequest.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_SETHHTTRIGOUTPUTENABLEDREQUEST_H
#define DOBOT_MESSAGE_SETHHTTRIGOUTPUTENABLEDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dobot
{
template <class ContainerAllocator>
struct SetHHTTrigOutputEnabledRequest_
{
  typedef SetHHTTrigOutputEnabledRequest_<ContainerAllocator> Type;

  SetHHTTrigOutputEnabledRequest_()
    : isEnabled(false)  {
    }
  SetHHTTrigOutputEnabledRequest_(const ContainerAllocator& _alloc)
    : isEnabled(false)  {
  (void)_alloc;
    }



   typedef uint8_t _isEnabled_type;
  _isEnabled_type isEnabled;





  typedef boost::shared_ptr< ::dobot::SetHHTTrigOutputEnabledRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dobot::SetHHTTrigOutputEnabledRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetHHTTrigOutputEnabledRequest_

typedef ::dobot::SetHHTTrigOutputEnabledRequest_<std::allocator<void> > SetHHTTrigOutputEnabledRequest;

typedef boost::shared_ptr< ::dobot::SetHHTTrigOutputEnabledRequest > SetHHTTrigOutputEnabledRequestPtr;
typedef boost::shared_ptr< ::dobot::SetHHTTrigOutputEnabledRequest const> SetHHTTrigOutputEnabledRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dobot::SetHHTTrigOutputEnabledRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dobot::SetHHTTrigOutputEnabledRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dobot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'dobot': ['/home/kermit/dobot_ws/src/dobot/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dobot::SetHHTTrigOutputEnabledRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot::SetHHTTrigOutputEnabledRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot::SetHHTTrigOutputEnabledRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot::SetHHTTrigOutputEnabledRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot::SetHHTTrigOutputEnabledRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot::SetHHTTrigOutputEnabledRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dobot::SetHHTTrigOutputEnabledRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "49d7f356a678a99078140911ab6e6d2a";
  }

  static const char* value(const ::dobot::SetHHTTrigOutputEnabledRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x49d7f356a678a990ULL;
  static const uint64_t static_value2 = 0x78140911ab6e6d2aULL;
};

template<class ContainerAllocator>
struct DataType< ::dobot::SetHHTTrigOutputEnabledRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dobot/SetHHTTrigOutputEnabledRequest";
  }

  static const char* value(const ::dobot::SetHHTTrigOutputEnabledRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dobot::SetHHTTrigOutputEnabledRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool isEnabled\n"
;
  }

  static const char* value(const ::dobot::SetHHTTrigOutputEnabledRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dobot::SetHHTTrigOutputEnabledRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.isEnabled);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetHHTTrigOutputEnabledRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dobot::SetHHTTrigOutputEnabledRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dobot::SetHHTTrigOutputEnabledRequest_<ContainerAllocator>& v)
  {
    s << indent << "isEnabled: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isEnabled);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOBOT_MESSAGE_SETHHTTRIGOUTPUTENABLEDREQUEST_H
