// Generated by gencpp from file dobot/SetHHTTrigOutputEnabled.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_SETHHTTRIGOUTPUTENABLED_H
#define DOBOT_MESSAGE_SETHHTTRIGOUTPUTENABLED_H

#include <ros/service_traits.h>


#include <dobot/SetHHTTrigOutputEnabledRequest.h>
#include <dobot/SetHHTTrigOutputEnabledResponse.h>


namespace dobot
{

struct SetHHTTrigOutputEnabled
{

typedef SetHHTTrigOutputEnabledRequest Request;
typedef SetHHTTrigOutputEnabledResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetHHTTrigOutputEnabled
} // namespace dobot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot::SetHHTTrigOutputEnabled > {
  static const char* value()
  {
    return "39404d9e9bcc553c4bcaae6963186b7e";
  }

  static const char* value(const ::dobot::SetHHTTrigOutputEnabled&) { return value(); }
};

template<>
struct DataType< ::dobot::SetHHTTrigOutputEnabled > {
  static const char* value()
  {
    return "dobot/SetHHTTrigOutputEnabled";
  }

  static const char* value(const ::dobot::SetHHTTrigOutputEnabled&) { return value(); }
};


// service_traits::MD5Sum< ::dobot::SetHHTTrigOutputEnabledRequest> should match 
// service_traits::MD5Sum< ::dobot::SetHHTTrigOutputEnabled > 
template<>
struct MD5Sum< ::dobot::SetHHTTrigOutputEnabledRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::SetHHTTrigOutputEnabled >::value();
  }
  static const char* value(const ::dobot::SetHHTTrigOutputEnabledRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::SetHHTTrigOutputEnabledRequest> should match 
// service_traits::DataType< ::dobot::SetHHTTrigOutputEnabled > 
template<>
struct DataType< ::dobot::SetHHTTrigOutputEnabledRequest>
{
  static const char* value()
  {
    return DataType< ::dobot::SetHHTTrigOutputEnabled >::value();
  }
  static const char* value(const ::dobot::SetHHTTrigOutputEnabledRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot::SetHHTTrigOutputEnabledResponse> should match 
// service_traits::MD5Sum< ::dobot::SetHHTTrigOutputEnabled > 
template<>
struct MD5Sum< ::dobot::SetHHTTrigOutputEnabledResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::SetHHTTrigOutputEnabled >::value();
  }
  static const char* value(const ::dobot::SetHHTTrigOutputEnabledResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::SetHHTTrigOutputEnabledResponse> should match 
// service_traits::DataType< ::dobot::SetHHTTrigOutputEnabled > 
template<>
struct DataType< ::dobot::SetHHTTrigOutputEnabledResponse>
{
  static const char* value()
  {
    return DataType< ::dobot::SetHHTTrigOutputEnabled >::value();
  }
  static const char* value(const ::dobot::SetHHTTrigOutputEnabledResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_MESSAGE_SETHHTTRIGOUTPUTENABLED_H
