// Generated by gencpp from file dobot/GetHHTTrigOutputEnabledResponse.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_GETHHTTRIGOUTPUTENABLEDRESPONSE_H
#define DOBOT_MESSAGE_GETHHTTRIGOUTPUTENABLEDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dobot
{
template <class ContainerAllocator>
struct GetHHTTrigOutputEnabledResponse_
{
  typedef GetHHTTrigOutputEnabledResponse_<ContainerAllocator> Type;

  GetHHTTrigOutputEnabledResponse_()
    : isEnabled(false)
    , result(0)  {
    }
  GetHHTTrigOutputEnabledResponse_(const ContainerAllocator& _alloc)
    : isEnabled(false)
    , result(0)  {
  (void)_alloc;
    }



   typedef uint8_t _isEnabled_type;
  _isEnabled_type isEnabled;

   typedef int32_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::dobot::GetHHTTrigOutputEnabledResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dobot::GetHHTTrigOutputEnabledResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetHHTTrigOutputEnabledResponse_

typedef ::dobot::GetHHTTrigOutputEnabledResponse_<std::allocator<void> > GetHHTTrigOutputEnabledResponse;

typedef boost::shared_ptr< ::dobot::GetHHTTrigOutputEnabledResponse > GetHHTTrigOutputEnabledResponsePtr;
typedef boost::shared_ptr< ::dobot::GetHHTTrigOutputEnabledResponse const> GetHHTTrigOutputEnabledResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dobot::GetHHTTrigOutputEnabledResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dobot::GetHHTTrigOutputEnabledResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dobot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'dobot': ['/home/kermit/dobot_QRcode_ws/src/dobot/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dobot::GetHHTTrigOutputEnabledResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot::GetHHTTrigOutputEnabledResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot::GetHHTTrigOutputEnabledResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot::GetHHTTrigOutputEnabledResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot::GetHHTTrigOutputEnabledResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot::GetHHTTrigOutputEnabledResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dobot::GetHHTTrigOutputEnabledResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fffefdf4aa925b9b5df75fa9274cb7be";
  }

  static const char* value(const ::dobot::GetHHTTrigOutputEnabledResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfffefdf4aa925b9bULL;
  static const uint64_t static_value2 = 0x5df75fa9274cb7beULL;
};

template<class ContainerAllocator>
struct DataType< ::dobot::GetHHTTrigOutputEnabledResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dobot/GetHHTTrigOutputEnabledResponse";
  }

  static const char* value(const ::dobot::GetHHTTrigOutputEnabledResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dobot::GetHHTTrigOutputEnabledResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool isEnabled\n"
"int32 result\n"
"\n"
"\n"
;
  }

  static const char* value(const ::dobot::GetHHTTrigOutputEnabledResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dobot::GetHHTTrigOutputEnabledResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.isEnabled);
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetHHTTrigOutputEnabledResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dobot::GetHHTTrigOutputEnabledResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dobot::GetHHTTrigOutputEnabledResponse_<ContainerAllocator>& v)
  {
    s << indent << "isEnabled: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isEnabled);
    s << indent << "result: ";
    Printer<int32_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOBOT_MESSAGE_GETHHTTRIGOUTPUTENABLEDRESPONSE_H
