// Generated by gencpp from file dobot/GetHHTTrigOutputResponse.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_GETHHTTRIGOUTPUTRESPONSE_H
#define DOBOT_MESSAGE_GETHHTTRIGOUTPUTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dobot
{
template <class ContainerAllocator>
struct GetHHTTrigOutputResponse_
{
  typedef GetHHTTrigOutputResponse_<ContainerAllocator> Type;

  GetHHTTrigOutputResponse_()
    : isTriggered(false)
    , result(0)  {
    }
  GetHHTTrigOutputResponse_(const ContainerAllocator& _alloc)
    : isTriggered(false)
    , result(0)  {
  (void)_alloc;
    }



   typedef uint8_t _isTriggered_type;
  _isTriggered_type isTriggered;

   typedef int32_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::dobot::GetHHTTrigOutputResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dobot::GetHHTTrigOutputResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetHHTTrigOutputResponse_

typedef ::dobot::GetHHTTrigOutputResponse_<std::allocator<void> > GetHHTTrigOutputResponse;

typedef boost::shared_ptr< ::dobot::GetHHTTrigOutputResponse > GetHHTTrigOutputResponsePtr;
typedef boost::shared_ptr< ::dobot::GetHHTTrigOutputResponse const> GetHHTTrigOutputResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dobot::GetHHTTrigOutputResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dobot::GetHHTTrigOutputResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dobot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'dobot': ['/home/kermit/dobot_QRcode_ws/src/dobot/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dobot::GetHHTTrigOutputResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot::GetHHTTrigOutputResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot::GetHHTTrigOutputResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot::GetHHTTrigOutputResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot::GetHHTTrigOutputResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot::GetHHTTrigOutputResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dobot::GetHHTTrigOutputResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1946bbc3a20603520250b54a04604eab";
  }

  static const char* value(const ::dobot::GetHHTTrigOutputResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1946bbc3a2060352ULL;
  static const uint64_t static_value2 = 0x0250b54a04604eabULL;
};

template<class ContainerAllocator>
struct DataType< ::dobot::GetHHTTrigOutputResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dobot/GetHHTTrigOutputResponse";
  }

  static const char* value(const ::dobot::GetHHTTrigOutputResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dobot::GetHHTTrigOutputResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool isTriggered\n"
"int32 result\n"
"\n"
;
  }

  static const char* value(const ::dobot::GetHHTTrigOutputResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dobot::GetHHTTrigOutputResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.isTriggered);
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetHHTTrigOutputResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dobot::GetHHTTrigOutputResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dobot::GetHHTTrigOutputResponse_<ContainerAllocator>& v)
  {
    s << indent << "isTriggered: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isTriggered);
    s << indent << "result: ";
    Printer<int32_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOBOT_MESSAGE_GETHHTTRIGOUTPUTRESPONSE_H
