// Generated by gencpp from file dobot/GetHHTTrigModeResponse.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_GETHHTTRIGMODERESPONSE_H
#define DOBOT_MESSAGE_GETHHTTRIGMODERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dobot
{
template <class ContainerAllocator>
struct GetHHTTrigModeResponse_
{
  typedef GetHHTTrigModeResponse_<ContainerAllocator> Type;

  GetHHTTrigModeResponse_()
    : tagHHTTrigMode(0)
    , result(0)  {
    }
  GetHHTTrigModeResponse_(const ContainerAllocator& _alloc)
    : tagHHTTrigMode(0)
    , result(0)  {
  (void)_alloc;
    }



   typedef uint8_t _tagHHTTrigMode_type;
  _tagHHTTrigMode_type tagHHTTrigMode;

   typedef int32_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::dobot::GetHHTTrigModeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dobot::GetHHTTrigModeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetHHTTrigModeResponse_

typedef ::dobot::GetHHTTrigModeResponse_<std::allocator<void> > GetHHTTrigModeResponse;

typedef boost::shared_ptr< ::dobot::GetHHTTrigModeResponse > GetHHTTrigModeResponsePtr;
typedef boost::shared_ptr< ::dobot::GetHHTTrigModeResponse const> GetHHTTrigModeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dobot::GetHHTTrigModeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dobot::GetHHTTrigModeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dobot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'dobot': ['/home/kermit/dobot_QRcode_ws/src/dobot/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dobot::GetHHTTrigModeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dobot::GetHHTTrigModeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot::GetHHTTrigModeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dobot::GetHHTTrigModeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot::GetHHTTrigModeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dobot::GetHHTTrigModeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dobot::GetHHTTrigModeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1abcbcf9addf5b1ea080766e6d75545f";
  }

  static const char* value(const ::dobot::GetHHTTrigModeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1abcbcf9addf5b1eULL;
  static const uint64_t static_value2 = 0xa080766e6d75545fULL;
};

template<class ContainerAllocator>
struct DataType< ::dobot::GetHHTTrigModeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dobot/GetHHTTrigModeResponse";
  }

  static const char* value(const ::dobot::GetHHTTrigModeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dobot::GetHHTTrigModeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 tagHHTTrigMode\n"
"int32 result\n"
"\n"
;
  }

  static const char* value(const ::dobot::GetHHTTrigModeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dobot::GetHHTTrigModeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tagHHTTrigMode);
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetHHTTrigModeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dobot::GetHHTTrigModeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dobot::GetHHTTrigModeResponse_<ContainerAllocator>& v)
  {
    s << indent << "tagHHTTrigMode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.tagHHTTrigMode);
    s << indent << "result: ";
    Printer<int32_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DOBOT_MESSAGE_GETHHTTRIGMODERESPONSE_H
