// Generated by gencpp from file dobot/GetHHTTrigOutputEnabled.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_GETHHTTRIGOUTPUTENABLED_H
#define DOBOT_MESSAGE_GETHHTTRIGOUTPUTENABLED_H

#include <ros/service_traits.h>


#include <dobot/GetHHTTrigOutputEnabledRequest.h>
#include <dobot/GetHHTTrigOutputEnabledResponse.h>


namespace dobot
{

struct GetHHTTrigOutputEnabled
{

typedef GetHHTTrigOutputEnabledRequest Request;
typedef GetHHTTrigOutputEnabledResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetHHTTrigOutputEnabled
} // namespace dobot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot::GetHHTTrigOutputEnabled > {
  static const char* value()
  {
    return "fffefdf4aa925b9b5df75fa9274cb7be";
  }

  static const char* value(const ::dobot::GetHHTTrigOutputEnabled&) { return value(); }
};

template<>
struct DataType< ::dobot::GetHHTTrigOutputEnabled > {
  static const char* value()
  {
    return "dobot/GetHHTTrigOutputEnabled";
  }

  static const char* value(const ::dobot::GetHHTTrigOutputEnabled&) { return value(); }
};


// service_traits::MD5Sum< ::dobot::GetHHTTrigOutputEnabledRequest> should match 
// service_traits::MD5Sum< ::dobot::GetHHTTrigOutputEnabled > 
template<>
struct MD5Sum< ::dobot::GetHHTTrigOutputEnabledRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::GetHHTTrigOutputEnabled >::value();
  }
  static const char* value(const ::dobot::GetHHTTrigOutputEnabledRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::GetHHTTrigOutputEnabledRequest> should match 
// service_traits::DataType< ::dobot::GetHHTTrigOutputEnabled > 
template<>
struct DataType< ::dobot::GetHHTTrigOutputEnabledRequest>
{
  static const char* value()
  {
    return DataType< ::dobot::GetHHTTrigOutputEnabled >::value();
  }
  static const char* value(const ::dobot::GetHHTTrigOutputEnabledRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot::GetHHTTrigOutputEnabledResponse> should match 
// service_traits::MD5Sum< ::dobot::GetHHTTrigOutputEnabled > 
template<>
struct MD5Sum< ::dobot::GetHHTTrigOutputEnabledResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::GetHHTTrigOutputEnabled >::value();
  }
  static const char* value(const ::dobot::GetHHTTrigOutputEnabledResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::GetHHTTrigOutputEnabledResponse> should match 
// service_traits::DataType< ::dobot::GetHHTTrigOutputEnabled > 
template<>
struct DataType< ::dobot::GetHHTTrigOutputEnabledResponse>
{
  static const char* value()
  {
    return DataType< ::dobot::GetHHTTrigOutputEnabled >::value();
  }
  static const char* value(const ::dobot::GetHHTTrigOutputEnabledResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_MESSAGE_GETHHTTRIGOUTPUTENABLED_H
