// Generated by gencpp from file dobot/SetColorSensor.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_SETCOLORSENSOR_H
#define DOBOT_MESSAGE_SETCOLORSENSOR_H

#include <ros/service_traits.h>


#include <dobot/SetColorSensorRequest.h>
#include <dobot/SetColorSensorResponse.h>


namespace dobot
{

struct SetColorSensor
{

typedef SetColorSensorRequest Request;
typedef SetColorSensorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetColorSensor
} // namespace dobot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot::SetColorSensor > {
  static const char* value()
  {
    return "2bf2a7c11ddc2a48c7a0f63413545e80";
  }

  static const char* value(const ::dobot::SetColorSensor&) { return value(); }
};

template<>
struct DataType< ::dobot::SetColorSensor > {
  static const char* value()
  {
    return "dobot/SetColorSensor";
  }

  static const char* value(const ::dobot::SetColorSensor&) { return value(); }
};


// service_traits::MD5Sum< ::dobot::SetColorSensorRequest> should match 
// service_traits::MD5Sum< ::dobot::SetColorSensor > 
template<>
struct MD5Sum< ::dobot::SetColorSensorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::SetColorSensor >::value();
  }
  static const char* value(const ::dobot::SetColorSensorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::SetColorSensorRequest> should match 
// service_traits::DataType< ::dobot::SetColorSensor > 
template<>
struct DataType< ::dobot::SetColorSensorRequest>
{
  static const char* value()
  {
    return DataType< ::dobot::SetColorSensor >::value();
  }
  static const char* value(const ::dobot::SetColorSensorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot::SetColorSensorResponse> should match 
// service_traits::MD5Sum< ::dobot::SetColorSensor > 
template<>
struct MD5Sum< ::dobot::SetColorSensorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::SetColorSensor >::value();
  }
  static const char* value(const ::dobot::SetColorSensorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::SetColorSensorResponse> should match 
// service_traits::DataType< ::dobot::SetColorSensor > 
template<>
struct DataType< ::dobot::SetColorSensorResponse>
{
  static const char* value()
  {
    return DataType< ::dobot::SetColorSensor >::value();
  }
  static const char* value(const ::dobot::SetColorSensorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_MESSAGE_SETCOLORSENSOR_H
