// Generated by gencpp from file dobot/SetHHTTrigMode.msg
// DO NOT EDIT!


#ifndef DOBOT_MESSAGE_SETHHTTRIGMODE_H
#define DOBOT_MESSAGE_SETHHTTRIGMODE_H

#include <ros/service_traits.h>


#include <dobot/SetHHTTrigModeRequest.h>
#include <dobot/SetHHTTrigModeResponse.h>


namespace dobot
{

struct SetHHTTrigMode
{

typedef SetHHTTrigModeRequest Request;
typedef SetHHTTrigModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetHHTTrigMode
} // namespace dobot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dobot::SetHHTTrigMode > {
  static const char* value()
  {
    return "856f63db51d715161eae0ac2b7d97f56";
  }

  static const char* value(const ::dobot::SetHHTTrigMode&) { return value(); }
};

template<>
struct DataType< ::dobot::SetHHTTrigMode > {
  static const char* value()
  {
    return "dobot/SetHHTTrigMode";
  }

  static const char* value(const ::dobot::SetHHTTrigMode&) { return value(); }
};


// service_traits::MD5Sum< ::dobot::SetHHTTrigModeRequest> should match 
// service_traits::MD5Sum< ::dobot::SetHHTTrigMode > 
template<>
struct MD5Sum< ::dobot::SetHHTTrigModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::SetHHTTrigMode >::value();
  }
  static const char* value(const ::dobot::SetHHTTrigModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::SetHHTTrigModeRequest> should match 
// service_traits::DataType< ::dobot::SetHHTTrigMode > 
template<>
struct DataType< ::dobot::SetHHTTrigModeRequest>
{
  static const char* value()
  {
    return DataType< ::dobot::SetHHTTrigMode >::value();
  }
  static const char* value(const ::dobot::SetHHTTrigModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dobot::SetHHTTrigModeResponse> should match 
// service_traits::MD5Sum< ::dobot::SetHHTTrigMode > 
template<>
struct MD5Sum< ::dobot::SetHHTTrigModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dobot::SetHHTTrigMode >::value();
  }
  static const char* value(const ::dobot::SetHHTTrigModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dobot::SetHHTTrigModeResponse> should match 
// service_traits::DataType< ::dobot::SetHHTTrigMode > 
template<>
struct DataType< ::dobot::SetHHTTrigModeResponse>
{
  static const char* value()
  {
    return DataType< ::dobot::SetHHTTrigMode >::value();
  }
  static const char* value(const ::dobot::SetHHTTrigModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DOBOT_MESSAGE_SETHHTTRIGMODE_H
